version: '2'

services:
  postgres-db:
    image: 'postgres:13.1-alpine'
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpasswd
      - POSTGRES_DB=testdb
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - dj_postgres_data:/var/lib/postgresql/data/

  thymeleaf-demo:
    image: 'belpanos/thymeleaf-demo:latest'
    build:
      context: .
      dockerfile: nonroot.Dockerfile
    container_name: thymeleaf-demo
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

volumes:
  dj_postgres_data: